# Generated by Django 5.0.6 on 2024-05-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratransactionmodel',
            name='include_in_statistics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regulartransactionmodel',
            name='include_in_statistics',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='regulartransactionmodel',
            name='period',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Work-Day', 'Work-Day')], max_length=15),
        ),
    ]
