# Generated by Django 5.0.6 on 2024-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_extratransactionmodel_include_in_statistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyaccountmodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
