# Generated by Django 5.0.6 on 2024-05-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_moneyaccountmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyaccountmodel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
