# Generated by Django 5.0.6 on 2024-05-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_moneyaccountmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyaccountmodel',
            name='show_in_overview',
            field=models.BooleanField(default=True),
        ),
    ]
