# Generated by Django 5.0.6 on 2024-05-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_moneyaccountmodel_show_in_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyaccountmodel',
            name='include_in_statistics',
            field=models.BooleanField(default=True),
        ),
    ]
