# Generated by Django 5.0.6 on 2024-12-30 20:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_historicalcategorymodel_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('negative_ledger_name', models.CharField(max_length=150)),
                ('positive_ledger_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLedgerName',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('negative_ledger_name', models.CharField(max_length=150)),
                ('positive_ledger_name', models.CharField(blank=True, max_length=150, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ledger name',
                'verbose_name_plural': 'historical ledger names',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='ledger_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.ledgername'),
        ),
        migrations.AddField(
            model_name='extratransactionmodel',
            name='ledger_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.ledgername'),
        ),
        migrations.AddField(
            model_name='historicalcategorymodel',
            name='ledger_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.ledgername'),
        ),
        migrations.AddField(
            model_name='historicalextratransactionmodel',
            name='ledger_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.ledgername'),
        ),
        migrations.AddField(
            model_name='historicalmoneyaccountmodel',
            name='ledger_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.ledgername'),
        ),
        migrations.AddField(
            model_name='historicalregulartransactionmodel',
            name='ledger_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.ledgername'),
        ),
        migrations.AddField(
            model_name='historicaltagmodel',
            name='ledger_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.ledgername'),
        ),
        migrations.AddField(
            model_name='moneyaccountmodel',
            name='ledger_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.ledgername'),
        ),
        migrations.AddField(
            model_name='regulartransactionmodel',
            name='ledger_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.ledgername'),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='ledger_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.ledgername'),
        ),
    ]
