# Generated by Django 5.0.6 on 2024-12-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_ledgername_historicalledgername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalledgername',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgername',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
